pipeline {
    agent any

    stages {
        // stage('terraform plan') {
        //     steps {
        //         sh "aws s3 sync --delete ./resume-site/* s3://blb-main-bucket"
        //     }
        // }

        stage('S3 Sync') {
            steps {
                sh "aws s3 sync --delete ./resume-site/* s3://blb-main-bucket"
            }
        }
    }
}
